---
collections:
  - name: amazon.aws
    version: 9.5.2
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
  - name: ansible.controller
    version: 4.7.4
  - name: ansible.platform
    version: 2.6.20250924
  - name: infra.aap_configuration
    version: 3.8.3
  - name: community.general
    version: 12.0.1
  - name: redhat.rhel_system_roles
    version: 1.108.6
  - name: ansible.hub
    version: 1.0.2
  - name: ansible.eda
    version: 2.10.0
  - name: containers.podman
    version: "1.18.0"
  - name: community.hashi_vault
    version: "7.1.0"
  - name: community.crypto
    version: "3.0.5"
